<?php
require_once __DIR__.'/database.php';require_once __DIR__.'/security.php';
require_once dirname(__DIR__).'/vendor/autoload.php';
use Firebase\JWT\JWT;use Firebase\JWT\Key;
function mc_jwt_key(): string { $k=(string)getenv('JWT_SECRET');if(strlen($k)<32)throw new RuntimeException('JWT_SECRET ausente ou muito curto.');return $k; }
function mc_cookie_options(int $expires): array { $https=((($_SERVER['HTTP_X_FORWARDED_PROTO']??'')==='https')||(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off'));$s=strtolower((string)(getenv('COOKIE_SECURE')?:''));if(in_array($s,['1','true','yes'],true))$https=true;if(in_array($s,['0','false','no'],true))$https=false;$o=['expires'=>$expires,'path'=>'/','httponly'=>true,'secure'=>$https,'samesite'=>'Lax'];$d=trim((string)(getenv('COOKIE_DOMAIN')?:''));if($d!=='')$o['domain']=$d;return $o; }
function mc_issue_auth_cookie(array $u): string { $now=time();$ttl=60*60*24*30;$p=['iat'=>$now,'nbf'=>$now,'exp'=>$now+$ttl,'id'=>(int)$u['id'],'role'=>(string)($u['role']??'CUSTOMER'),'email'=>(string)($u['email']??''),'name'=>(string)($u['name']??'')];$jwt=JWT::encode($p,mc_jwt_key(),'HS256');setcookie('metalcolor_auth',$jwt,mc_cookie_options($now+$ttl));$_COOKIE['metalcolor_auth']=$jwt;return $jwt; }
function mc_clear_auth_cookie(): void { setcookie('metalcolor_auth','',mc_cookie_options(time()-3600));unset($_COOKIE['metalcolor_auth']); }
function mc_current_user(?PDO $pdo=null): ?array { $t=$_COOKIE['metalcolor_auth']??'';if($t==='')return null;try{$d=JWT::decode($t,new Key(mc_jwt_key(),'HS256'));$pdo=$pdo?:mc_pdo();mc_ensure_schema($pdo);$st=$pdo->prepare('SELECT id,name,email,role,phone,cpf_cnpj FROM metalcolor_users WHERE id=:id LIMIT 1');$st->execute([':id'=>(int)$d->id]);$u=$st->fetch();if(!$u){mc_clear_auth_cookie();return null;}return $u;}catch(Throwable $e){mc_clear_auth_cookie();return null;} }
function mc_verify_password_and_upgrade(PDO $pdo,array $u,string $password): bool { $stored=(string)($u['password_hash']??'');if($stored!==''&&password_verify($password,$stored)){if(password_needs_rehash($stored,PASSWORD_DEFAULT)){$h=password_hash($password,PASSWORD_DEFAULT);$pdo->prepare('UPDATE metalcolor_users SET password_hash=:p,updated_at=NOW() WHERE id=:id')->execute([':p'=>$h,':id'=>(int)$u['id']]);}return true;}return false; }
function mc_record_login(PDO $pdo,int $id): void { try{$pdo->prepare('INSERT INTO metalcolor_user_logins(user_id,ip) VALUES(:id,:ip)')->execute([':id'=>$id,':ip'=>mc_client_ip()]);}catch(Throwable $e){} }
function mc_is_admin(?array $u): bool { return $u && (($u['role']??'')==='ADMIN'); }
